backend/apps/about/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.author, name='author'),
    path('contact/', views.contact, name='contact'),
]

backend/apps/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_swagger.views import get_swagger_view

from .views import FilmViewSet

schema_view = get_swagger_view(title='Схема API проекта Δиа Фильм²')


router = DefaultRouter()
router.register(r'films', FilmViewSet, basename='diafilms')

urlpatterns = [
    path('v1/', include(router.urls)),
    path('v1/docs/', schema_view, name='swagger-ui'),
]

backend/apps/posts/urls.py
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.decorators.cache import cache_page

from . import sitemaps, views

sitemaps = {
    'posts': sitemaps.PostsSitemap,
    'groups': sitemaps.GroupsSitemap,
    'tags': sitemaps.TagsSitemap,
}

urlpatterns = [
    # sitemaps
    path('sitemap.xml',
         cache_page(86400)(sitemaps_views.index),
         {'sitemaps': sitemaps, 'sitemap_url_name': 'posts:sitemaps'}),
    path('sitemap-<section>.xml',
         cache_page(86400)(sitemaps_views.sitemap),
         {'sitemaps': sitemaps}, name='sitemaps'),

    # Основное
    path('', views.post_list, name='index'),
    path('diafilms/random/', views.diafilms_random, name='diafilms_random'),
    path('groups/', views.group_list, name='group_list'),
    path('group/<slug:group_slug>/', views.group_detail, name='group_detail'),
    path('tags/', views.tag_list, name='tag_list'),
    path('tag/<slug:tag_category_slug>/<slug:tag_slug>/',
         views.tag_detail, name='tag_detail'),
    path('search/', views.post_search, name='post_search'),
    path('follow/', views.follow_index, name='post_follow_list'),

    # Профиль
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='follow_user'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='unfollow_user'),

    # Посты
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/', views.post, name='post'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/comment/delete/<int:comment_id>/',
         views.delete_comment, name='delete_comment'),
]

backend/apps/user/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import SignUp

urlpatterns = [

    path('login/',
         views.LoginView.as_view(template_name='users/login.html'),
         name='login'),

    path('signup/',
         SignUp.as_view(template_name='users/signup.html'),
         name='signup'),

    path('logout/',
         views.LogoutView.as_view(
             template_name='users/logged_out.html'),
         name='logout'),

    path('password_change/',
         views.PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change'),

    path('password_change/done/',
         views.PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         views.PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset'),

    path('password_reset/done/',
         views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_complete'),
]

backend/diafilm/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.posts.urls', 'posts'), namespace=None)),
    path('api/', include(('apps.api.urls', 'api'), namespace='api')),
    path('about/', include(('apps.about.urls', 'about'), namespace='about')),
    path('auth/', include(('apps.user.urls', 'users'), namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),

    # django-debug-toolbar
    path('__debug__/', include(debug_toolbar.urls)),
]

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

backend/apps/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class GroupCategory(models.Model):

    name = models.CharField(
        max_length=120,
        unique=True,
        verbose_name='Имя категории постов',
    )

    slug = models.SlugField(
        max_length=120,
        unique=True,
        verbose_name='Slug категории постов',
    )

    description = models.TextField(
        blank=True,
        verbose_name='Описание категории постов',
    )

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return f'{self.name}'


class Post(models.Model):

    text = models.TextField(
        verbose_name='Текст',
        help_text='Напишите текст поста',
    )

    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации поста',
        help_text='Укажите дату публикации поста',
    )

    modified_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата последней редакции поста',
        help_text='Дате последней редакции поста',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
        help_text='Укажите автора поста',
    )

    groups = models.ManyToManyField(
        GroupCategory,
        related_name="posts",
        verbose_name='Группы, которые присвоены посту',
        help_text='Укажите группу (группы) поста',
    )

    tags = models.ManyToManyField(
        'Tag',
        related_name="posts",
        verbose_name='Тэги, которые присвоены посту',
        help_text='Укажите тэг (тэги) поста',
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return f'{self.text[:15]}'


class TagCategory(models.Model):

    name = models.CharField(
        max_length=120,
        unique=True,
        verbose_name='Имя категории тэгов',
    )

    slug = models.SlugField(
        max_length=120,
        unique=True,
        verbose_name='Slug категории тэгов',
    )

    class Meta:
        verbose_name = 'Категория тэгов'
        verbose_name_plural = 'Категории тэгов'

    def __str__(self):
        return f'{self.name}'


class Tag(models.Model):

    name = models.CharField(
        max_length=120,
        verbose_name='Имя тэгa',
    )

    slug = models.SlugField(
        max_length=120,
        verbose_name='Slug тэгa',
    )

    category = models.ForeignKey(
        TagCategory,
        related_name='tags',
        on_delete=models.CASCADE,
        help_text='Группа тэгов, к которому присвоен тэг',
    )

    class Meta:
        unique_together = ('name', 'category')
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'

    def __str__(self):
        return f'{self.name}'


class Comment(models.Model):

    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Напишите текст комментария',
    )

    post = models.ForeignKey(
        Post,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='comments',
        verbose_name='Комменты поста',
        help_text='Укажите пост коммента',
    )

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации комментария',
        help_text='Укажите дату и время публикации комментария',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комменты пользователя',
        help_text='Укажите автора коммента',
    )

    class Meta:
        verbose_name = 'Коммент'
        verbose_name_plural = 'Комменты'

    def __str__(self):
        return f'{self.text[:15]}'


class Follow(models.Model):

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подпискa пользователя',
        help_text='Укажите пользователя подписки',
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Подписка на пользователя',
        help_text='Укажите пользователя на которого подписываются',
    )

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата подписки',
        help_text='Укажите дату и время начала подписки на пользователя',
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.user}'

backend/apps/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
            'groups',
            'image',
        )
        labels = {
            'text': 'Текст нового поста',
            'groups': 'Выберете группу, к которой будет относиться пост',
            'image': 'Картинка поста',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст нового коммента',
        }

backend/posts/forms.py
from django import forms

from .models import Comment, Post, GroupCategory


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
            'groups',
            'image',
        )
        labels = {
            'text': 'Текст нового поста',
            'groups': 'Выберете группу, к которой будет относиться пост',
            'image': 'Картинка поста',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст нового коммента',
        }

backend/templates/includes/comment_form.html
{% load static %}
<div class="container mt-4 px-0">
  <div class="row d-flex justify-content-left">
    <div class="col-md-12">
      <div class="card p-3 my-2">
        <form method="post" class="comment_form" action="{% url "posts:add_comment" post_id=post.id %}">
          <div class="d-flex">
            <img src="{% static 'img/logo.png' %}" width="30" class="user-img rounded-circle mr-2">
            <h5 class="mx-2">Добавить комментарий:</h5>
          </div>
          <div class="d-flex justify-content-between align-items-center">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст коммента
                <span class="required text-danger">*</span>
              </label>
              {{ form.text }}
              <small id="id_text-help" class="form-text text-muted">
                {{ form.text.help_text }}
              </small>
            </div>
          </div>
          {% include "includes/form_errors.html" %}
          <div class="action d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">Добавить коммент</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

backend/templates/includes/comments.html
{% load static %}
<div class="container mt-4">
  <div class="row d-flex justify-content-left">
    <div class="col-md-10">
      {% for comment in post.comments.all %}
      <div class="card p-3 my-2">
        <div class="d-flex justify-content-between align-items-center">
          <div class="user d-flex flex-row align-items-center">
            <!-- <img src="{% static 'img/logo.png' %}" width="30" class="user-img rounded-circle mr-2"> -->
            <span>
              <small class="font-weight-bold text-primary mx-2">
                <span class="highlight-text-color">
                  <i class="bi bi-person-fill"></i>
                </span>
                <b>
                  <a href="{% url "posts:profile" username=comment.author.username %}">{{ comment.author.username }}</a>
                </b>
              </small>
            </span>
            <small>{{ comment.created }}</small>
          </div>
        </div>
        <p class="mx-2">{{ comment.text }}</p>
        {% if comment.author == request.user %}
        <div class="action d-flex justify-content-end">
          <small>
            <a class="btn btn-danger btn-sm"
              href="{% url "posts:delete_comment" post_id=post.id comment_id=comment.id %}">Удалить</a>
          </small>
        </div>
        {% endif %}
      </div>
      {% endfor %}
    </div>
  </div>
</div>

backend/templates/includes/content-bar.html
<div class="row">
  <div class="col-sm-12 col-lg-6 col-xl-5 pb-2 justify-content-left">
    <a href="{% url "posts:post_search" %}" class="btn btn-secondary btn-sm" role="button">
      <i class="bi bi-search"></i> Поиск
    </a>
    <a href="{% url "posts:group_list" %}" class="btn btn-secondary btn-sm" role="button">
      <i class="bi bi-folder"></i> Все группы
    </a>
    <a href="{% url "posts:tag_list" %}" class="btn btn-secondary btn-sm" role="button">
      <i class="bi bi-tag"></i> Все тэги
    </a>
  </div>
  <div class="col-sm-12 col-lg-6 col-xl-7">
    {% if post_view %}
    {% include 'includes/paginator.html' with url_vars="&post_view=True" %}
    {% else %}
    {% include 'includes/paginator.html' %}
    {% endif %}
  </div>
</div>

backend/templates/includes/footer.html
{% load cache %}
{% cache 6000 footer %}
<!-- Подвал, сгенерировано с помощью pug-->
<footer class="border-top">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#!">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="
                    fab
                    fa-twitter fa-stack-1x fa-inverse
                  "></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://github.com/mbrav">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <div class="small text-center text-muted fst-italic">
          Диафильмы предоставлены
          <a href="https://diafilmy.su/">Diafilmy.su</a>
        </div>
        <div class="small text-center text-muted fst-italic">
          <a href="{% url "about:author" %}">Проект «Δиа Фильм²»</a> не связан никаким-либо образом с
          «Diafilmy.su»
        </div>
        <div class="small text-center text-muted fst-italic">
          Copyright &copy; <span class="highlight-text-color">Δиа</span> <span style="color:black">Фильм²</span> 2021
        </div>
      </div>
    </div>
  </div>
</footer>
{% endcache %}

backend/templates/includes/form_errors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger alert-dismissible" role="alert">
  {{ error|escape }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-warning alert-dismissible" role="alert">
  {{ error|escape }}
</div>
{% endfor %}
{% endif %}

backend/templates/includes/group_card.html
{% load cache %}
{% cache 6000 post_card_thumbnail group %}
<div class="col">
  <div class="card shadow-sm">
    {% if group.image %}
    {% load thumbnail %}
    {% thumbnail post.image "300x150" crop="center" as im %}
    <img src="{{ im.url }}" class="card-img-top">
    {% endthumbnail %}
    {% else %}
    <img src="{{ group.posts.last.cover.image.url }}" class="card-img-top">
    {% endif %}
    <!-- <h4>{{ group.posts.all.0.cover.image.url}}</h4> -->
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-center">
        <div class="user d-flex flex-row align-items-center">
          <h5 class="card-title">
            <a href="{% url "posts:group_detail" group_slug=group.slug %}"><i>{{ group.name }}</i></a>
          </h5>
          <p>{{ group.posts.all.count }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endcache %}

backend/templates/includes/navbar.html
{% load static %}
<!-- Навигация, сгенерировано с помощью pug-->
<nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href='{% url "posts:index" %}'><span class="highlight-text-color">Δиа</span> Фильм²</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
      aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Меню
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "posts:post_search" %}">
            <i class="bi bi-search"></i> Поиск
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "posts:post_follow_list" %}">Подписки</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "posts:post_create" %}">
            Новая запись
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "posts:profile" username=user.get_username %}">
            <i class="bi bi-person-fill"></i>
            {{ user.get_username }}
          </a>
        </li>
        {% if user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="/admin">
            Админка
          </a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "users:password_change" %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "users:logout" %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "users:login" %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "users:signup" %}">Регистрация</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "about:author" %}">О проекте</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "api:swagger-ui" %}">API</a>
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url "about:contact" %}">Контакт</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

backend/templates/includes/paginator.html
<!-- нет черты после последнего поста -->
<!-- если записей больше 10 подключён паджинатор -->
{% if page_obj.has_other_pages %}
<nav>
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page=1{{ url_vars }}">
        <!-- <i class="bi bi-chevron-double-left"></i> -->
        <i class="bi bi-chevron-bar-left"></i>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ url_vars }}">
        <i class="bi bi-chevron-compact-left"></i>
      </a>
    </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}</span>
    </li>
    {% elif i|add:"3" > page_obj.number and i|add:"-3" < page_obj.number %} <li class="page-item">
      <a class="page-link" href="?page={{ i }}{{ url_vars }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}{{ url_vars }}">
        <i class="bi bi-chevron-compact-right"></i>
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{{ url_vars }}">
        <!-- <i class="bi bi-chevron-double-right"></i> -->
        <i class="bi bi-chevron-bar-right"></i>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

backend/templates/includes/post_card.html
{% load cache %}
{% cache 6000 card_thumbnail post post.modified_at %}
<div class="col">
  <div class="card shadow-sm">
    {% if post.image %}
    {% load thumbnail %}
    {% thumbnail post.image "300x150" crop="center" as im %}
    <img src="{{ im.url }}" class="card-img-top">
    {% endthumbnail %}
    {% else %}
    <img src="{{ post.cover.image.url }}" class="card-img-top">
    {% endif %}
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-center">
        <div class="user d-flex flex-row align-items-center">
          {% if post_view %}
          <h5 class="card-title">
            <a href="{% url "posts:profile" username=post.author.username %}">Автор: {{ post.author }}</a>
          </h5>
          {% else %}
          <h5 class="card-title">
            <a href="{% url "posts:post" post_id=post.id %}"><i>{{ post.name }}</i></a>
          </h5>
          {% endif %}
        </div>
      </div>
      <h6 class="card-subtitle mb-2 text-muted">
        <i class="bi bi-calendar-event"></i> {{ post.pub_date }}
      </h6>
      {% for cat in post.groups.all %}
      <a class="btn btn-outline-secondary btn-sm"
        href="{% url "posts:group_detail" group_slug=cat.slug %}{% if post_view %}?post_view=True{% endif %}">
        <i class="bi bi-folder"></i>
        {{ cat }}
      </a>
      {% endfor %}
      <p class="card-text">{{ post.text|truncatewords:30 }}</p>
      <div class="btn-group">
        <a class="btn btn-sm btn-outline-primary" href="{% url "posts:post" post_id=post.id %}">
          <i class="bi bi-eye"></i> Просмотр
        </a>
      </div>
    </div>
  </div>
</div>
{% endcache %}

backend/templates/includes/post_form.html
<div class="card">
  <div class="card-header">{{ form_tile|default:"Форма поста" }}</div>
  <div class="card-body">
    {% if post.id %}
    <form method="post" action="{% url "posts:post_edit" post_id=post.id %}" enctype="multipart/form-data">
      {% else %}
      <form method="post" action="{% url "posts:post_create" %}" enctype="multipart/form-data">
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        {% comment %} <div class="form-group row my-3 p-3">
          <label for="id_text">
            Текст поста
            <span class="required text-danger">*</span>
          </label>
          {{ form.text }}
          <small id="id_text-help" class="form-text text-muted">
            {{ form.text.help_text }}
          </small>
        </div>
        <div class="form-group row my-3 p-3">
          <label for="id_groups"> Группа </label>
          {{ form.groups }}
          <small id="id_group-help" class="form-text text-muted">
            {{ form.groups.help_text }}
          </small>
        </div>
        <div class="form-group row my-3 p-3">
          <label for="id_image"> Изображение </label>
          {{ form.image }}
          <small id="id_image-help" class="form-text text-muted">
            {{ form.image.help_text }}
          </small>
        </div> {% endcomment %}
        {% include "includes/form_errors.html" %}
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
      </form>
  </div>
</div>

backend/templates/includes/post_is_diafilm.html
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-10">
      <a id="full-screen-toggle" class="btn btn-warning btn" role="button">
        <h4><i class="bi bi-arrows-fullscreen"> </i>На весь экран</h4>
      </a>
      <div class="carousel slide" id="diafilm-carousel" data-bs-ride="carousel">
        <div class="carousel-inner">
          {% for frame in frames.all %}
          {% if forloop.first %}
          <div class="carousel-item active">
            <img class="d-block" style="width:100%" src="{{ frame.url }}" alt="Кадр №{{ frame.sequence }}" />
          </div>
          {% else %}
          <div class="carousel-item">
            <img class="d-block" style="width:100%" src="{{ frame.url }}" alt="Кадр №{{ frame.sequence }}" />
          </div>
          {% endif %}
          {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#diafilm-carousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#diafilm-carousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <span class="caption text-muted">
        Используйте кнопку ◀ и ▶ для навигации по слайдам.
      </span>
    </div>
  </div>
</div>
<div class="container">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-11 col-lg-9">
      <div class="container">
        <div class="row">
          <div class="col">
            <p>
              {% for tag in post.tags.all %}
              <span class="highlight-text-color">
                <i class="bi bi-tag"></i>
              </span>
              <b> {{ tag.category }}:</b>
              {% comment %} <a href="{% url "posts:tag_detail" tag_categeory_slug=tag.category.slug tag_slug=tag.slug
                %}"> {% endcomment %}
                <a href="/tag/{{tag.category.slug}}/{{tag.slug}}/">
                  <i>{{ tag.name }}</i>
                </a>
                <br />
                {% endfor %}
            </p>
          </div>
          <div class="col">
            <p>
              <b>Студия:</b>
              <i>«{{ post.studio }}»</i>
              <br />
              <b>Название:</b>
              <i>«{{ post.name }}»</i>
              <br />
              <b>Год:</b>
              {{ post.year }}
              <br />
              <b>Кадров:</b>
              <i>{{ frames.count }}</i>
              <br />
              <b>Индекс:</b>
              {{ post.index }}
              <br />
              <b>Номер:</b>
              {{ post.number }}
              <br />
              <b>Цвет:</b>
              {{ post.color }}
              <br />
              <b>Качество:</b>
              {{ post.quality }}
              <br />
              <b>Плёнка:</b>
              {{ post.film }}
              <br />
              <b>Тип Плёнки:</b>
              {{ post.film_type }}
              <br />
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

backend/templates/includes/switcher.html
<div class="row my-3">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
        <i class="bi bi-files"></i> Все Записи
      </a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link {% if following %}active{% endif %}" href="{% url 'posts:post_follow_list' %}">
        <i class="bi bi-broadcast"></i> Подписки
      </a>
    </li>
    {% endif %}
    <li class="nav-item">
      <div class="btn-group btn-group" role="group" aria-label="Basic checkbox toggle button group">
        <a class="btn btn{% if post_view %}-outline-{% else %}-{% endif %}primary" href=".">
          <i class="bi bi-film"></i> Диафильмы
        </a>
        <a class="btn btn{% if post_view %}-{% else %}-outline-{% endif %}primary" href="?post_view=True">
          <i class="bi bi-file-post"></i> Посты
        </a>
      </div>
    </li>
  </ul>
</div>