backend/apps/user/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import SignUp

urlpatterns = [

    path('login/',
         views.LoginView.as_view(template_name='users/login.html'),
         name='login'),

    path('signup/',
         SignUp.as_view(template_name='users/signup.html'),
         name='signup'),

    path('logout/',
         views.LogoutView.as_view(
             template_name='users/logged_out.html'),
         name='logout'),

    path('password_change/',
         views.PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change'),

    path('password_change/done/',
         views.PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/',
         views.PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset'),

    path('password_reset/done/',
         views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('reset/done/',
         views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_complete'),
]

backend/diafilm/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.posts.urls', 'posts'), namespace=None)),
    path('api/', include(('apps.api.urls', 'api'), namespace='api')),
    path('about/', include(('apps.about.urls', 'about'), namespace='about')),
    path('auth/', include(('apps.user.urls', 'users'), namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),

    # django-debug-toolbar
    path('__debug__/', include(debug_toolbar.urls)),
]

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

backend/apps/about/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.EmailField(label='Имя', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Почта', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    subject = forms.CharField(label='Тема', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    message = forms.CharField(label='Сообщение', widget=forms.TextInput(
        attrs={'class': 'form-control', 'style': 'height: 12rem'}))

    def __str__(self):
        return self.email

backend/apps/user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

backend/apps/user/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

backend/templates/users/logged_out.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Вы вышли из системы
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Выход</div>
        <div class="card-body">
          <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
</div>
{% endblock %}

backend/templates/users/login.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Войти
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Войти на сайт</div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="form-group row my-3">
              <label for="id_username">
                Имя пользователя
                <span class="required text-danger">*</span>
              </label>
              <input
                type="text"
                name="username"
                autofocus
                class="form-control"
                required
                id="id_username"
              />
            </div>
            <div class="form-group row my-3">
              <label for="id_password">
                Пароль
                <span class="required text-danger">*</span>
              </label>
              <input
                type="password"
                name="password"
                class="form-control"
                required
                id="id_password"
              />
            </div>
            {% include "includes/form_errors.html" %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a
                href="{% url "users:password_reset" %}"
                class="btn btn-link"
              >
                Забыли пароль?
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

backend/templates/users/password_change_done.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Пароль изменён
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Пароль изменён</div>
        <div class="card-body">
          <p>Пароль изменён успешно</p>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
</div>
{% endblock %}

backend/templates/users/password_change_form.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Изменение пароля
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Изменить пароль</div>
        <div class="card-body">
          <form
            method="post"
            action="{% url "users:password_change" %}"
          >
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_old_password">
                Старый пароль
                <span class="required text-danger">*</span>
              </label>
              <input
                type="password"
                name="old_password"
                autofocus
                class="form-control"
                required
                id="id_old_password"
              />
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>
              <input
                type="password"
                name="new_password1"
                class="form-control"
                required
                id="id_new_password1"
              />
              <small
                id="id_new_password1-help"
                class="form-text text-muted"
              >
                <ul>
                  <li>
                    Ваш пароль не должен совпадать с вашим
                    именем или другой персональной
                    информацией или быть слишком похожим на
                    неё.
                  </li>
                  <li>
                    Ваш пароль должен содержать как минимум
                    8 символов.
                  </li>
                  <li>
                    Ваш пароль не может быть одним из широко
                    распространённых паролей.
                  </li>
                  <li>
                    Ваш пароль не может состоять только из
                    цифр.
                  </li>
                </ul>
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>
              <input
                type="password"
                name="new_password2"
                class="form-control"
                required
                id="id_new_password2"
              />
            </div>
            {% include "includes/form_errors.html" %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
</div>
{% endblock %}

backend/templates/users/password_reset_complete.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Сброс пароля прошёл успешно
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Восстановление пароля завершено</div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url "users:login" %}">войти</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

backend/templates/users/password_reset_confirm.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Новый пароль
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Введите новый пароль</div>
        <div class="card-body">
          <form
            method="post"
            action="{% url "users:password_reset_confirm" %}"
          >
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>
              <input
                type="password"
                name="new_password1"
                class="form-control"
                required
                id="id_new_password1"
              />
              <small
                id="id_new_password1-help"
                class="form-text text-muted"
              >
                <ul>
                  <li>
                    Ваш пароль не должен совпадать с вашим
                    именем или другой персональной
                    информацией или быть слишком похожим на
                    неё.
                  </li>
                  <li>
                    Ваш пароль должен содержать как минимум
                    8 символов.
                  </li>
                  <li>
                    Ваш пароль не может быть одним из широко
                    распространённых паролей.
                  </li>
                  <li>
                    Ваш пароль не может состоять только из
                    цифр.
                  </li>
                </ul>
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>
              <input
                type="password"
                name="new_password2"
                class="form-control"
                required
                id="id_new_password2"
              />
            </div>
            {% include "includes/form_errors.html" %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
  <!-- если использована неправильная ссылка -->
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Ошибка</div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
  <!-- конец если использована неправильная ссылка -->
</div>
{% endblock %}

backend/templates/users/password_reset_done.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Сброс пароля прошёл успешно
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Отправлено письмо</div>
        <div class="card-body">
          <p>
            Проверьте свою почту, вам должно прийти письмо со
            ссылкой для восстановления пароля
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

backend/templates/users/password_reset_form.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Сброс пароля
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной
          почты, под которым вы регистрировались
        </div>
        <div class="card-body">
          <form
            method="post"
            action="{% url "users:password_reset" %}"
          >
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>
              <input
                type="email"
                name="email"
                maxlength="254"
                class="form-control"
                required
                id="id_email"
              />
            </div>
            {% include "includes/form_errors.html" %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

backend/templates/users/signup.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Регистрация
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">
          <form method="post" action="{% url "users:signup" %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_first_name">Имя</label>
              {{ form.first_name }}
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_last_name">Фамилия</label>
              {{ form.last_name }}
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_username">
                Имя пользователя
                <span class="required text-danger">*</span>
              </label>
              {{ form.username }}
              <small
                id="id_username-help"
                class="form-text text-muted"
              >
                Обязательное поле. Не более 150 символов. Только
                буквы, цифры и символы @/./+/-/_.
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_email"
                >Адрес электронной почты</label
              >
              {{ form.email }}
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_password1">
                Пароль
                <span class="required text-danger">*</span>
              </label>
              {{ form.password1 }}
              <small
                id="id_password1-help"
                class="form-text text-muted"
              >
                <ul>
                  <li>
                    Ваш пароль не должен совпадать с вашим
                    именем или другой персональной
                    информацией или быть слишком похожим на
                    неё.
                  </li>
                  <li>
                    Ваш пароль должен содержать как минимум
                    8 символов.
                  </li>
                  <li>
                    Ваш пароль не может быть одним из широко
                    распространённых паролей.
                  </li>
                  <li>
                    Ваш пароль не может состоять только из
                    цифр.
                  </li>
                </ul>
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_password2">
                Подтверждение пароля
                <span class="required text-danger">*</span>
              </label>
              {{ form.password2 }}
              <small
                id="id_password2-help"
                class="form-text text-muted"
              >
                Для подтверждения введите, пожалуйста, пароль
                ещё раз.
              </small>
            </div>
            {% include "includes/form_errors.html" %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
</div>
{% endblock %}