backend/apps/about/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.author, name='author'),
    path('contact/', views.contact, name='contact'),
]

backend/diafilm/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.posts.urls', 'posts'), namespace=None)),
    path('api/', include(('apps.api.urls', 'api'), namespace='api')),
    path('about/', include(('apps.about.urls', 'about'), namespace='about')),
    path('auth/', include(('apps.user.urls', 'users'), namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),

    # django-debug-toolbar
    path('__debug__/', include(debug_toolbar.urls)),
]

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

backend/apps/about/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.EmailField(label='Имя', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Почта', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    subject = forms.CharField(label='Тема', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    message = forms.CharField(label='Сообщение', widget=forms.TextInput(
        attrs={'class': 'form-control', 'style': 'height: 12rem'}))

    def __str__(self):
        return self.email

backend/about/views.py
from django.shortcuts import render
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string 
from django.views.decorators.cache import cache_page

from diafilm.settings import EMAIL_HOST_USER
from .forms import ContactForm


@cache_page(60 * 15)
def author(request):
    return render(request, 'about/author.html')


@cache_page(60 * 15)
def contact(request):
    contact_form = ContactForm()
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)

        subject, from_email = 'hello', EMAIL_HOST_USER
        to = str(contact_form['email'].value())
        subject = contact_form['subject'].value()
        name = contact_form['name'].value()
        text_content = contact_form['message'].value()

        context = {
            'name': name,
            'email': to,
            'subject': subject,
            'message': text_content,
        }

        html_template = 'about/emails/contact.html'
        html_content = render_to_string(html_template, context)

        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        return render(request, 'about/author.html', {'recepient': to})

    context = {
        'form': contact_form,
    }
    return render(request, 'about/contact.html', context)

backend/apps/about/views.py
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.decorators.cache import cache_page

from diafilm.settings import EMAIL_HOST_USER

from .forms import ContactForm


@cache_page(60 * 15)
def author(request):
    return render(request, 'about/author.html')


@cache_page(60 * 15)
def contact(request):
    contact_form = ContactForm()
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)

        subject, from_email = 'hello', EMAIL_HOST_USER
        to = str(contact_form['email'].value())
        subject = contact_form['subject'].value()
        name = contact_form['name'].value()
        text_content = contact_form['message'].value()

        context = {
            'name': name,
            'email': to,
            'subject': subject,
            'message': text_content,
        }

        html_template = 'about/emails/contact.html'
        html_content = render_to_string(html_template, context)

        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        return render(request, 'about/author.html', {'recepient': to})

    context = {
        'form': contact_form,
    }
    return render(request, 'about/contact.html', context)

backend/templates/about/author.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | О проекте
{% endblock%}
{% load static %}
{% load cache %}
{% block content %}
{% cache 6000 author %}
<!-- Шапка Страницы-->
<header class="masthead py-6" style="background-image: url('{% static 'img/bg/bg-4.jpg' %}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>О проекте</h1>
          <h2><span class="highlight-text-color">Δиа</span> Фильм²</h2>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Основной Контент-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          «<span class="highlight-text-color">Δиа</span>
          <span style="color: black">Фильм²</span>» –
          проект, который разрабатывался для курса
          <a href="https://praktikum.yandex.ru/">Яндекс Практикум</a>
          . Не исключено, что проект получит дальнейшее внимание и его
          развитие продолжится. На данный момент проект будет сохранен
          в том виде, в котором он сейчас находится.
        </p>
        <p>
          Контент был взят с сайта
          <a href="https://diafilmy.su/">Diafilmy.su</a>
          и сформирован с использованием различных скриптов, код
          которых <a
            href="https://github.com/mbrav/diafilm2/blob/main/backend/diafilms/management/commands/film_scrape.py">доступен
            здесь</a>. Сам проект «Δиа Фильм²» не связан
          никаким-либо образом с «Diafilmy.su». Используемая тема:
          <a href="https://github.com/StartBootstrap/startbootstrap-clean-blog">Start Bootstrap - Clean Blog</a>
          .
        </p>
      </div>
    </div>
  </div>
</main>
{% endcache %}
{% endblock %}

backend/templates/about/contact.html
{% extends '../base.html' %}
{% block title %}
Δиа Фильм² | Контакт
{% endblock %}
{% load static %}
{% load cache %}
{% block content %}
{% cache 6000 contact %}
<!-- Шапка Страницы-->
<header class="masthead py-6" style="background-image: url('{% static 'img/bg/bg-2.jpg' %}')">
	<div class="container position-relative px-4 px-lg-5">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
				<div class="page-heading">
					<h1>Контакт</h1>
					<span class="subheading">Есть Вопросы? Свяжитесь!</span>
				</div>
			</div>
		</div>
	</div>
</header>
<!-- Основной Контент-->
<main class="mb-4">
	<div class="container px-4 px-lg-5">
		<div class="row gx-4 gx-lg-5 justify-content-center">
			<div class="col-md-10 col-lg-8 col-xl-7">
				<p>
					Хотите с нами связаться? Вот моя контактная информация, я
					свяжусь с вами как можно скорее!
				</p>
				<a class="btn btn-outline-primary btn-lg" href="https://t.me/absurdcomrade">
					<i class="bi bi-telegram"></i>
					Telegram
				</a>
				<a class="btn btn-outline-secondary btn-lg" href="mailto:mbraverman96@gmail.com">
					<i class="bi bi-envelope"></i>
					Почта
				</a>
				<a class="btn btn-outline-secondary btn-lg" href="https://github.com/mbrav">
					<i class="bi bi-github"></i>
					Github
				</a>
				{% comment %}
				<div class="my-5">
					<form method="post">
						{% csrf_token %}
						<div class="form-floating">
							{{ form.name }}
							<label for="id_name">{{ form.name.label }}</label>
						</div>
						<div class="form-floating">
							{{ form.email }}
							<label for="id_email">{{ form.email.label }}</label>
						</div>
						<div class="form-floating">
							{{ form.subject }}
							<label for="id_subject">{{ form.subject.label }}</label>
						</div>
						<div class="form-floating">
							{{ form.message }}
							<label for="id_message">{{ form.message.label }}</label>
						</div>
						{% include "includes/form_errors.html" %}
						<br />
						<button type="submit" class="btn btn-primary text-uppercase">
							Отправить
						</button>
					</form>
				</div>
				{% endcomment %}
			</div>
		</div>
	</div>
</main>
{% endcache %} {% endblock %}